// <auto-generated />
using System;
using BucketOfThoughts.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BucketOfThoughts.Data.Migrations
{
    [DbContext(typeof(BucketOfThoughtsDbContext))]
    partial class BucketOfThoughtsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BucketOfThoughts.Data.Entities.LoginProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Auth0Id")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(2);

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("ModifiedDateTime")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.HasIndex("Auth0Id")
                        .IsUnique();

                    b.ToTable("LoginProfile");
                });

            modelBuilder.Entity("BucketOfThoughts.Data.Entities.RelatedThought", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(2);

                    b.Property<long>("ParentThoughtId")
                        .HasColumnType("bigint");

                    b.Property<long>("RelatedThoughtId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ParentThoughtId");

                    b.HasIndex("RelatedThoughtId");

                    b.ToTable("RelatedThoughts");
                });

            modelBuilder.Entity("BucketOfThoughts.Data.Entities.Thought", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(2);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("LoginProfileId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(4);

                    b.Property<DateTimeOffset?>("ModifiedDateTime")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(3);

                    b.Property<bool>("ShowOnDashboard")
                        .HasColumnType("bit");

                    b.Property<string>("TextType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<long>("ThoughtBucketId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ThoughtDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ThoughtGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LoginProfileId");

                    b.HasIndex("ThoughtBucketId");

                    b.ToTable("Thoughts");
                });

            modelBuilder.Entity("BucketOfThoughts.Data.Entities.ThoughtBucket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(2);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long>("LoginProfileId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(4);

                    b.Property<DateTimeOffset?>("ModifiedDateTime")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(3);

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<bool>("ShowOnDashboard")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<long>("ThoughtModuleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LoginProfileId");

                    b.HasIndex("ThoughtModuleId");

                    b.ToTable("ThoughtBuckets");
                });

            modelBuilder.Entity("BucketOfThoughts.Data.Entities.ThoughtDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(2);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedDateTime")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(3);

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<long>("ThoughtId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ThoughtId");

                    b.ToTable("ThoughtDetails");
                });

            modelBuilder.Entity("BucketOfThoughts.Data.Entities.ThoughtModule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(2);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("ThoughtModules");
                });

            modelBuilder.Entity("BucketOfThoughts.Data.Entities.ThoughtWebsiteLink", b =>
                {
                    b.Property<long>("ThoughtId")
                        .HasColumnType("bigint");

                    b.Property<long>("WebsiteLinkId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("ThoughtId", "WebsiteLinkId");

                    b.HasIndex("WebsiteLinkId");

                    b.ToTable("ThoughtWebsiteLinks");
                });

            modelBuilder.Entity("BucketOfThoughts.Data.Entities.WebsiteLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(2);

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("ModifiedDateTime")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(3);

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("WebsiteUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("WebsiteLinks");
                });

            modelBuilder.Entity("BucketOfThoughts.Data.Entities.RelatedThought", b =>
                {
                    b.HasOne("BucketOfThoughts.Data.Entities.Thought", "ParentThought")
                        .WithMany("RelatedThoughts")
                        .HasForeignKey("ParentThoughtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BucketOfThoughts.Data.Entities.Thought", "RelatedThoughtEntity")
                        .WithMany("ParentLinks")
                        .HasForeignKey("RelatedThoughtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParentThought");

                    b.Navigation("RelatedThoughtEntity");
                });

            modelBuilder.Entity("BucketOfThoughts.Data.Entities.Thought", b =>
                {
                    b.HasOne("BucketOfThoughts.Data.Entities.LoginProfile", "LoginProfile")
                        .WithMany("Thoughts")
                        .HasForeignKey("LoginProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BucketOfThoughts.Data.Entities.ThoughtBucket", "Bucket")
                        .WithMany("Thoughts")
                        .HasForeignKey("ThoughtBucketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bucket");

                    b.Navigation("LoginProfile");
                });

            modelBuilder.Entity("BucketOfThoughts.Data.Entities.ThoughtBucket", b =>
                {
                    b.HasOne("BucketOfThoughts.Data.Entities.LoginProfile", "LoginProfile")
                        .WithMany("ThoughtBuckets")
                        .HasForeignKey("LoginProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BucketOfThoughts.Data.Entities.ThoughtModule", "ThoughtModule")
                        .WithMany("ThoughtBuckets")
                        .HasForeignKey("ThoughtModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoginProfile");

                    b.Navigation("ThoughtModule");
                });

            modelBuilder.Entity("BucketOfThoughts.Data.Entities.ThoughtDetail", b =>
                {
                    b.HasOne("BucketOfThoughts.Data.Entities.Thought", "Thought")
                        .WithMany("Details")
                        .HasForeignKey("ThoughtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Thought");
                });

            modelBuilder.Entity("BucketOfThoughts.Data.Entities.ThoughtWebsiteLink", b =>
                {
                    b.HasOne("BucketOfThoughts.Data.Entities.Thought", "Thought")
                        .WithMany("WebsiteLinks")
                        .HasForeignKey("ThoughtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BucketOfThoughts.Data.Entities.WebsiteLink", "WebsiteLink")
                        .WithMany("ThoughtWebsiteLinks")
                        .HasForeignKey("WebsiteLinkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Thought");

                    b.Navigation("WebsiteLink");
                });

            modelBuilder.Entity("BucketOfThoughts.Data.Entities.LoginProfile", b =>
                {
                    b.Navigation("ThoughtBuckets");

                    b.Navigation("Thoughts");
                });

            modelBuilder.Entity("BucketOfThoughts.Data.Entities.Thought", b =>
                {
                    b.Navigation("Details");

                    b.Navigation("ParentLinks");

                    b.Navigation("RelatedThoughts");

                    b.Navigation("WebsiteLinks");
                });

            modelBuilder.Entity("BucketOfThoughts.Data.Entities.ThoughtBucket", b =>
                {
                    b.Navigation("Thoughts");
                });

            modelBuilder.Entity("BucketOfThoughts.Data.Entities.ThoughtModule", b =>
                {
                    b.Navigation("ThoughtBuckets");
                });

            modelBuilder.Entity("BucketOfThoughts.Data.Entities.WebsiteLink", b =>
                {
                    b.Navigation("ThoughtWebsiteLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
