name: Build-Push-Development

on:
  push:
    branches: [ main ]
    paths-ignore: ['infra/**']

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    name: Deploy Development API
    runs-on: ubuntu-latest
    
    env:
      HASH: $(git rev-parse --short "$GITHUB_SHA")
      BRANCH: ${GITHUB_REF##*/}
      PROJECT_ID: '532956049186'
      PROJECT: bucket-of-thoughts-dev
      REGION: us-central1
      API_REPO: bucket-of-thoughts-api
      UI_REPO: bucket-of-thoughts-ui

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: 'google-github-actions/auth@v2'
        id: auth
        with:
          project_id: '${{ env.PROJECT_ID }}'
          workload_identity_provider: 'projects/${{ env.PROJECT_ID }}/locations/global/workloadIdentityPools/github/providers/github-oidc'
          service_account: 'github-actions-default@bucket-of-thoughts-dev.iam.gserviceaccount.com'
          token_format: 'access_token'

      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v3'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: '${{ env.REGION }}-docker.pkg.dev'

      - name: Docker Build API
        run: |
          docker build -f api.Dockerfile . -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT }}/${{ env.API_REPO }}/app:latest
          docker image tag ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT }}/${{ env.API_REPO }}/app:latest ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT }}/${{ env.API_REPO }}/app:${{ env.HASH }}
          docker image tag ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT }}/${{ env.API_REPO }}/app:latest ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT }}/${{ env.API_REPO }}/app:dev

      - name: Push API Image
        run: docker push -a ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT }}/${{ env.API_REPO }}/app

      - name: 'Deploy API'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: 'bucket-of-thoughts-api'
          project_id: '${{ env.PROJECT }}'
          image: '${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT }}/${{ env.API_REPO }}/app:latest'

     - name: Docker Build UI
        run: |
          docker build -f ui.Dockerfile . -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT }}/${{ env.UI_REPO }}/app:latest
          docker image tag ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT }}/${{ env.UI_REPO }}/app:latest ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT }}/${{ env.UI_REPO }}/app:${{ env.HASH }}
          docker image tag ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT }}/${{ env.UI_REPO }}/app:latest ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT }}/${{ env.UI_REPO }}/app:dev

      - name: Push UI Image
        run: docker push -a ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT }}/${{ env.UI_REPO }}/app