name: Build

on:
  push:
    branches-ignore: [ main ]
    paths-ignore: ['infra/**']

jobs:
  build:
    name: Build Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Build API
        run: |
          docker build -f api.Dockerfile .
         
      - name: Docker Build
        run: |
          docker build -f ui.Dockerfile .
